version: '3.8'
services:
  raft3d-node1:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - NODE_ID=node1
      - RAFT_PORT=9090
      - HTTP_PORT=8080
      - RAFT_DIR=/raft/data
      - CLUSTER=nodes=raft3d-node1:9090,raft3d-node2:9090,raft3d-node3:9090
    volumes:
      - raft-data:/raft/data
    networks:
      - raft3d-net

  raft3d-node2:
    build: .
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      - NODE_ID=node2
      - RAFT_PORT=9090
      - HTTP_PORT=8080
      - RAFT_DIR=/raft/data
      - CLUSTER=nodes=raft3d-node1:9090,raft3d-node2:9090,raft3d-node3:9090
    volumes:
      - raft-data:/raft/data
    networks:
      - raft3d-net

  raft3d-node3:
    build: .
    ports:
      - "8082:8080"
      - "9092:9090"
    environment:
      - NODE_ID=node3
      - RAFT_PORT=9090
      - HTTP_PORT=8080
      - RAFT_DIR=/raft/data
      - CLUSTER=nodes=raft3d-node1:9090,raft3d-node2:9090,raft3d-node3:9090
    volumes:
      - raft-data:/raft/data
    networks:
      - raft3d-net

volumes:
  raft-data:  # Single shared volume for all nodes

networks:
  raft3d-net:
    driver: bridge